function [res,gamma] = contifunc(index,m,size)


%%%% This is the a partly calculation for secular perturbation for 1/r^4 potential. Here, we provide the recurrence formulas for deriving the 
%%%% coefficients of -1/z^2M_{n-1}+Γ_nM_0. If needed, consider using recursion for the implementation.
%%%% Note: This function doesn't includes Δ, but including those generated by the
%%%% left-hand side of the equation. Input number index is M_{n-1}s 

coef = zeros(1,1);
coefm = zeros(1,1);
coefp = zeros(1,1);
res = zeros(1,size*2);
n = length(index);
%%%% For the 1st order
if  n == 1
    coef = -[1/(-4*m+4) * 1/(4*m*(m-1)), 1/(4+4*m) * 1/(4*m*(m+1))];
    gamma = 1/(2*(m-1)*(m+1));
    res((size-length(coef)/2+1):(size-length(coef)/2+length(coef))) = coef;
%%%% For the >2rd order
elseif mod(n,2) == 0
    k = n/2;
    A = ones(1,k);
    for i = 1:k
        coefm(i,i:i+2) = -index(i)*[1/(4*(m-(k-i+1)*2)*(m-(k-i+1)*2-1)), 1/(2*(m-(k-i+1)*2-1)*(m-(k-i+1)*2+1)), 1/(4*(m-(k-i+1)*2)*(m-(k-i+1)*2+1))];
    end
    coefmm = A * coefm;
    for i = (k+1):n
        coefp(i-k,(i-k):(i-k+2)) = -index(i)*[1/(4*(m+(i-k)*2)*((m+(i-k)*2)-1)),1/(2*((m+(i-k)*2)-1)*((m+(i-k)*2)+1)), 1/(4*((m+(i-k)*2))*((m+(i-k)*2)+1))];
    end
    coefpp = A * coefp;  
%%%% Calculation of Gamma and the right side of the eqn, the coeffcients
%%%% are list as J_{-n}, J_{-n+2}, ..., J_{-2}, J_{+2}, ..., J_{n}.
    gamma =-(coefmm(end)+coefpp(1));
    coefmnod = coefmm(1:end-1);
    coefpnod = coefpp(2:end);
    kk = length(coefmnod);
%%%% Plus Dm for each component
    for j = 1:kk
        coef(j) = 1/( 2*m*(-(kk-j+1)*2) + (-(kk-j+1)*2)^2 )*coefmnod(j);
        coef(j+kk) = 1/( 2*m*(2*j) + (2*j)^2  )*coefpnod(j);
    end

res((size-length(coef)/2+1):(size-length(coef)/2+length(coef))) = coef;





end

